name: lesson_center_backend
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.2.1
  html: ^0.14.0+2
#  moor: ^2.0.0
#  moor_ffi: ^0.0.1
#dependency_overrides:
#  analyzer: ^0.36.4
#  sqlite3:
#    git: https://github.com/dart-lang/sdk/tree/master/samples/ffi/sqlite
#    git: https://github.com/putraxor/dart-sqlite
  lessons_center_common:
    path: ../lessons_center_common

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
#  moor_generator: ^2.0.0