"""
Tests for audit_youtube_playlists.py
"""
import sys
import os
import unittest
from unittest.mock import MagicMock, patch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from audit_youtube_playlists import (
    get_series_doc_id,
    get_channel_playlists,
    audit_channel,
)


def _make_yt(playlists=None, uploads_id='UPabc'):
    yt = MagicMock()
    yt.channels.return_value.list.return_value.execute.return_value = {
        'items': [{'contentDetails': {'relatedPlaylists': {'uploads': uploads_id}}}]
    }
    yt.playlists.return_value.list.return_value.execute.return_value = {
        'items': [
            {
                'id': pl['id'],
                'snippet': {'title': pl['title']},
                'contentDetails': {'itemCount': pl['count']},
            }
            for pl in (playlists or [])
        ],
        'nextPageToken': None,
    }
    return yt


def _make_db(series_lesson_counts=None):
    """Fake db where count() returns the given count for each series_doc_id."""
    db = MagicMock()
    counts = series_lesson_counts or {}

    def _count_get():
        result = MagicMock()
        result.__getitem__ = lambda self, i: [MagicMock(value=0)]
        return result

    def _where(field, op, value):
        q = MagicMock()
        count_val = counts.get(value, 0)
        inner = MagicMock()
        inner.value = count_val
        q.count.return_value.get.return_value = [[inner]]
        return q

    db.collection.return_value.where.side_effect = _where
    return db


class TestGetSeriesDocId(unittest.TestCase):

    def test_deterministic_same_inputs(self):
        id1 = get_series_doc_id(63, 'PLabc123')
        id2 = get_series_doc_id(63, 'PLabc123')
        self.assertEqual(id1, id2)

    def test_different_playlist_gives_different_id(self):
        self.assertNotEqual(
            get_series_doc_id(63, 'PLaaa'),
            get_series_doc_id(63, 'PLbbb'),
        )

    def test_different_source_gives_different_id(self):
        self.assertNotEqual(
            get_series_doc_id(50, 'PLabc'),
            get_series_doc_id(63, 'PLabc'),
        )

    def test_starts_with_ser_prefix(self):
        self.assertTrue(get_series_doc_id(63, 'PLabc').startswith('ser_'))


class TestGetChannelPlaylists(unittest.TestCase):

    def test_returns_named_playlists(self):
        yt = _make_yt(
            playlists=[
                {'id': 'PL001', 'title': 'פרשת השבוע', 'count': 120},
                {'id': 'PL002', 'title': 'גמרא', 'count': 45},
            ],
            uploads_id='UPabc',
        )
        result = get_channel_playlists(yt, 'UCchannel', 'UPabc')
        self.assertEqual(len(result), 2)
        self.assertEqual(result[0]['youtube_count'], 120)

    def test_excludes_uploads_playlist(self):
        yt = _make_yt(
            playlists=[
                {'id': 'UPabc', 'title': 'Uploads', 'count': 500},  # excluded
                {'id': 'PL001', 'title': 'שיעורים', 'count': 30},
            ],
            uploads_id='UPabc',
        )
        result = get_channel_playlists(yt, 'UCchannel', 'UPabc')
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0]['id'], 'PL001')

    def test_excludes_uu_prefix_playlist(self):
        yt = _make_yt(
            playlists=[
                {'id': 'UUautogenerated', 'title': 'Auto', 'count': 100},
                {'id': 'PLreal', 'title': 'Real', 'count': 10},
            ],
            uploads_id='UPother',
        )
        result = get_channel_playlists(yt, 'UCchannel', 'UPother')
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0]['id'], 'PLreal')

    def test_youtube_count_included(self):
        yt = _make_yt(
            playlists=[{'id': 'PL001', 'title': 'Test', 'count': 99}],
            uploads_id='UPabc',
        )
        result = get_channel_playlists(yt, 'UCchannel', 'UPabc')
        self.assertEqual(result[0]['youtube_count'], 99)


class TestAuditChannel(unittest.TestCase):

    def test_no_gap_returns_empty_list(self):
        """When Firestore count == YouTube count, no gaps reported."""
        pl_id = 'PL001'
        series_doc_id = get_series_doc_id(50, pl_id)
        yt = _make_yt(
            playlists=[{'id': pl_id, 'title': 'פרשת השבוע', 'count': 100}],
            uploads_id='UPabc',
        )
        db = _make_db({series_doc_id: 100})
        gaps = audit_channel(db, yt, 50, 'UCchannel', 'Test Channel', threshold=0)
        self.assertEqual(gaps, [])

    def test_gap_above_threshold_is_reported(self):
        """When YouTube has more videos than Firestore, gap is reported."""
        pl_id = 'PL001'
        series_doc_id = get_series_doc_id(50, pl_id)
        yt = _make_yt(
            playlists=[{'id': pl_id, 'title': 'פרשת השבוע', 'count': 100}],
            uploads_id='UPabc',
        )
        db = _make_db({series_doc_id: 80})  # 20 missing
        gaps = audit_channel(db, yt, 50, 'UCchannel', 'Test Channel', threshold=0)
        self.assertEqual(len(gaps), 1)
        self.assertEqual(gaps[0]['gap'], 20)
        self.assertEqual(gaps[0]['youtube_count'], 100)
        self.assertEqual(gaps[0]['firestore_count'], 80)

    def test_gap_below_threshold_not_reported(self):
        """Gaps within tolerance are not flagged."""
        pl_id = 'PL001'
        series_doc_id = get_series_doc_id(50, pl_id)
        yt = _make_yt(
            playlists=[{'id': pl_id, 'title': 'Test', 'count': 100}],
            uploads_id='UPabc',
        )
        db = _make_db({series_doc_id: 97})  # gap of 3
        gaps = audit_channel(db, yt, 50, 'UCchannel', 'Test', threshold=5)
        self.assertEqual(gaps, [], "Gap of 3 should not be flagged when threshold=5")

    def test_gap_report_contains_required_fields(self):
        pl_id = 'PL001'
        series_doc_id = get_series_doc_id(50, pl_id)
        yt = _make_yt(
            playlists=[{'id': pl_id, 'title': 'פרשת השבוע', 'count': 50}],
            uploads_id='UPabc',
        )
        db = _make_db({series_doc_id: 30})
        gaps = audit_channel(db, yt, 50, 'UCchannel', 'Test Channel', threshold=0)
        self.assertEqual(len(gaps), 1)
        g = gaps[0]
        for field in ['source_id', 'channel', 'playlist_id', 'playlist_title',
                      'series_doc_id', 'youtube_count', 'firestore_count', 'gap']:
            self.assertIn(field, g, f"Missing field: {field}")
        self.assertEqual(g['series_doc_id'], series_doc_id)

    def test_multiple_playlists_only_gaps_reported(self):
        pl1_id, pl2_id = 'PL001', 'PL002'
        sid1 = get_series_doc_id(50, pl1_id)
        sid2 = get_series_doc_id(50, pl2_id)
        yt = _make_yt(
            playlists=[
                {'id': pl1_id, 'title': 'Series A', 'count': 100},
                {'id': pl2_id, 'title': 'Series B', 'count': 50},
            ],
            uploads_id='UPabc',
        )
        db = _make_db({sid1: 100, sid2: 30})  # only Series B has gap
        gaps = audit_channel(db, yt, 50, 'UCchannel', 'Test', threshold=0)
        self.assertEqual(len(gaps), 1)
        self.assertEqual(gaps[0]['playlist_id'], pl2_id)
        self.assertEqual(gaps[0]['gap'], 20)

    def test_channel_not_found_returns_empty(self):
        yt = MagicMock()
        yt.channels.return_value.list.return_value.execute.return_value = {'items': []}
        db = _make_db()
        gaps = audit_channel(db, yt, 50, 'UCmissing', 'Missing', threshold=0)
        self.assertEqual(gaps, [])


if __name__ == '__main__':
    unittest.main()
